book/book.tex

In chapter 1, `preg_map` doesn't exist yet when it is used by `indices = preg_map[caseid]`. This commit adds a line to create `preg_map` using `MakePregMap()`.

Make preg_map using MakePregMap() before using it.

---

code/setup.py

This will allow you to conveniently publish `thinkstats2` and `thinkplot` modules on PyPI.  This way people can then just `pip install thinkstats2` and be able to import those two modules.
Thanks a bunch for a very nice book and useful library.  :-)

Add setup.py for thinkstats2 and thinkplot

---

book/book.tex

In the description of the method Percentile of the class Cdf, the argument is twice called `p` and once called `rank`. I propose to consistently call it `p` in all instances.

inconsistent naming of argument in description of Cdf.Percentile(p)

---

code/requirements.txt

On my MacOS 10.11.5 installation running python3, (not using anaconda), I got the following error:
```
$ virtualenv venv
$ source venv/bin/activate
$ python --version
$ python --version
Python 3.5.1
$ pip install -r requirements.txt
...
$ python nsfg.py 
numpy.dtype has the wrong size, try recompiling
```
After the included change:
```
$ virtualenv venv
$ source venv/bin/activate
$ pip install -r requirements.txt
...
$ python nsfg.py 
(13593, 244)
nsfg.py: All tests passed.
```
I haven't gotten to other examples from the book, so I'm not sure if anything else is broken. If so, I'll just switch to using anaconda instead.

Update numpy version to work with this version of pandas.

---

code/nsfg.py

Following error is printed on running: 
`(13593, 244)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/home/ashish/Documents/ashish/ThinkStats2/code/nsfg.py in <module>()
if __name__ == '__main__':
main()
NameError: name 'script' is not defined
`
Fixed this error, by removing the script from print statement.

Removed 'script' from the print statement

---

book/book.tex

In the section on correlation:
`Transform each value to a {\bf standard scores}` -> `Transform each value to a {\bf standard score}` ->

Fix a typo (remove an unnecessary `s`)

---

CONTRIBUTING.md

Fix the link in CONTRIBUTING.md to the Github issues tab.

Fix link to issues tab

---

code/chap04soln.ipynb

It appears that the incorrect `cdf` was chosen for the `first` dataset.

Use first_cdf instead of cdf for first-born percentile rank

---

code/thinkstats2_test.py

This is now 4 characters shorter than previously expected. I'm guessing
that this is because the first numpy array may have changed from
"[1, 2, 3, 5]" to "[1., 2., 3., 5.,]".

Fix test of str representation of new Cdf object

---

book/book.tex

The variable name for pregnancy order should be `pregordr`, not `pregorder`.

Fix variable name for pregnancy order

---

book/book.tex

This fixes the layout of 3 blocks in the 'Exploratory data analysis'
chapter.

Replace tabs with spaces in verbatim environments

---

book/book.tex

Without this its not easy to navigate to the index in PDF version.

Add Index entry to Table of Contents

---

book/book.tex

One occurance of this. Fix to make consistent.

Display `hinc_soln.py` as \tt not \url

---

book/book.tex

This was missing in one early paragraph. Elswhere it is formated with
\tt.

Fix missing \tt format for filename `nsfg.py`

---

code/chap01ex.ipynb

The data index returned by pandas is indeed 5515, but the caseid is 5012 (see solutions)

Responded caseid should be 5012, not 5515

---

CONTRIBUTING.md

The `conda activate` command  has been the preferred since version 4.4 (released around December 2017). In short, the old `source activate` command does not work reliably in all environments and may not even be available in newer installations. The new `conda activate` command resolves those issues.
The note is a minimal change to help with this. You may want to consider inverting this at some point: making `conda activate` the main instruction and adding a not about versions earlier than 4.4.

Add 'activate' note for conda versions from 4.4

---

book/book.tex

These are used inconsistently throughout the document, even in the same
paragraph. Prefer the \verb"" form as it gives more semantic context for
post-processors (e.g. pandoc).

Prefer inline \verb"" to {\tt} expressions

---

book/book.tex

The keys for the first chapter glossary are bold, but later glossaries
are not. Make them all bold to be consistent. (The bold version looks
better IMHO).

Make "keys" in glossaries bold consistently

---

.gitignore
book/Makefile

This strips line numbers from the hevea build logs for purposes of comparison.

BLD: tee hevea output to build.log, `make hevea-compare-logs`

---

book/book.tex

The book recommends you make a copy of `estimation.py` to complete the chapter 8 exercises.
While we could do this, the other chapters thus far point to a Jupyter notebook for end of chapter exercises.
Since there is a Jupyter notebook for chapter 8: `chap08ex.ipynb`, I suggest we refer readers to that notebook instead of `estimation.py`. The end of chapter exercises in the book chapter are the same as those in the chapter 8 notebook.

Updating code location for chapter 8's exercises

---

code/chap06ex.ipynb

Original notebook throws the following warning from `InterpolateSample`:
```
/home/downey/anaconda3/envs/ModSimPy/lib/python3.6/site-packages/ipykernel_launcher.py:26: DeprecationWarning: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.
```
Looks like this is fully deprecated in new versions, breaking the notebook. Casting `row.freq` to an `int` fixes the issue. Cells afterward then work as intended.
Should `row.freq` be rounded instead of truncated? I don't think so but I leave that decision to the experts.

#179 Fix - deprecated type passed to `np.linspace`

---

code/chap02ex.ipynb

The codebook URL at a cell in `chap02ex.ipynb` states [Cycle6Codebook-Pregnancy.pdf](ftp://ftp.cdc.gov/pub/Health_Statistics/NCHS/Dataset_Documentation/NSFG/Cycle6Codebook-Pregnancy.pdf) for code references, though it seems that it should be [Cycle6Codebook-Female.pdf](ftp://ftp.cdc.gov/pub/Health_Statistics/NCHS/Dataset_Documentation/NSFG/Cycle6Codebook-Female.pdf) instead.
The correct codes from that cell on (`totincr`, `numfmhh`, `parity`, `age_r`) all seem related to the **female** codebook.

Fixed codebook URL (chap02ex.ipynb)
